name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 8.15.0
        run_install: false

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - name: Setup pnpm cache
      uses: actions/cache@v3
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Check lockfile
      run: |
        chmod +x scripts/check-lockfile.sh
        ./scripts/check-lockfile.sh

    - name: Install dependencies
      run: |
        if [ -f pnpm-lock.yaml ]; then
          echo "Found pnpm-lock.yaml, installing with frozen lockfile"
          pnpm install --frozen-lockfile
        else
          echo "No pnpm-lock.yaml found, installing without frozen lockfile"
          pnpm install
        fi

    - name: Build
      run: pnpm run build:clean

    - name: Publish to NPM
      run: pnpm publish --no-git-checks
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ## 🚀 新版本发布
          
          ### 📦 安装方式
          ```bash
          npx juejin-mcp-server
          ```
          
          ### 🔗 相关链接
          - [NPM Package](https://www.npmjs.com/package/juejin-mcp-server)
          - [使用文档](https://github.com/h7ml/juejin-mcp-server/blob/main/README.md)
          - [API文档](https://github.com/h7ml/juejin-mcp-server/tree/main/docs)
          
          ### 📋 更新内容
          请查看 [CHANGELOG.md](https://github.com/h7ml/juejin-mcp-server/blob/main/CHANGELOG.md) 了解详细更新内容。
        draft: false
        prerelease: false
        
  docker:
    runs-on: ubuntu-latest
    needs: release
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: h7ml/juejin-mcp-server
        tags: |
          type=ref,event=tag
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64
